name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version

    - name: Install Google Chrome
      run: |
        wget -q -O google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome.deb || sudo apt-get install -f -y

    - name: Install Microsoft Edge
      run: |
        sudo apt-get update
        wget https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_134.0.3124.51-1_amd64.deb
        sudo apt install -y ./microsoft-edge-stable_134.0.3124.51-1_amd64.deb
        echo 'EDGE_BIN=/usr/bin/microsoft-edge' >> $GITHUB_ENV

    - name: Install ChromeDriver
      run: |
        wget https://storage.googleapis.com/chrome-for-testing-public/134.0.6998.35/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        chmod +x chromedriver-linux64/chromedriver
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/

    - name: Install EdgeDriver
      run: |
        wget https://msedgedriver.azureedge.net/134.0.3124.51/edgedriver_linux64.zip
        unzip edgedriver_linux64.zip 
        chmod +x msedgedriver 
        sudo mv msedgedriver /usr/local/bin/

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

        
    - name: Run tests
      run: |
        pytest  # Run tests using pytest
