name: Python CI

on:
  push:
    branches:
      - master  #Trigger on push to the 'main' branch
  pull_request:
    branches:
      - master  # Trigger on pull requests to the 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use a Linux environment for the job

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version (you can change this)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install ChromeDriver
      run: |
        wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/

    - name: Install Microsoft Edge
      run: |
        wget https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_132.0.2957.115-1_amd64.deb
        sudo dpkg -i microsoft-edge-stable_132.0.2957.115-1_amd64.deb
        sudo apt-get install -f

    - name: Install EdgeDriver
      run: |
        wget https://msedgedriver.azureedge.net/115.0.1901.183/edgedriver_linux64.zip
        unzip edgedriver_linux64.zip
        sudo mv msedgedriver /usr/local/bin/
        
    - name: Run tests
      run: |
        pytest  # Run tests using pytest
